name: Latest Blog Post Workflow

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Blog Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://codewithpres.hashnode.dev/rss.xml"
