name: Latest Blog Post Workflow

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Blogs
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://codewithpres.hashnode.dev/rss.xml"
